server:
  port: 80
spring:
#  mvc:
#    view:
#      suffix: .jsp
#      prefix: /WEB-INF/views/
  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
    cache: false
#    view-names: thymeleaf/*
